# Generated by Django 4.2.7 on 2026-01-20 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='resumes/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('predicted_role', models.CharField(blank=True, max_length=100, null=True)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('score', models.IntegerField(default=0)),
                ('extracted_skills', models.JSONField(blank=True, default=list)),
                ('recommended_skills', models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
